let num = 10
let num1 = 20
console.log("10 boln 20 hoyriin tentsuu baidal ")
console.log(num1==num)
console.log("10 bolon 20 hoyriin tentsuug turliin tesntsuu baidal")
console.log(num1===num)
console.log("10 bolon 20 hoyriin tentsuu bus baidal")
console.log(num1!=num)
console.log("zuun taliin utga ni baruun talaas ih bvl true butsaan")
console.log(num1>num)
console.log("zuun taliin utga ni baruun taliin utgaas baga baivl true butsaan")
console.log(num1<num)
console.log("hariu ni true")
console.log(!false && true)
console.log("bas l true")
console.log(!false || true)
console.log("enl false")
console.log(false&&true)
